version: "3"

services:
  css_db:
    image: mysql
    environment:
      MYSQL_DATABASE: css_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-init/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./mysql-init/data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "33060:3306"
    restart: on-failure
