version: "3"

services:
  css_db:
    image: mysql
    environment:
      MYSQL_DATABASE: css_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-init/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "33060:3306"
    restart: on-failure
    command: # 명령어 실행 (한글 깨짐 방지)
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
