version: "3"

services:
  css_app:
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    restart: on-failure
    depends_on:
      - css_db

  css_db:
    image: mysql
    environment:
      MYSQL_DATABASE: css_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-init/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "33060:3306"
    restart: on-failure
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
